### PR TITLE
grammar fixes, smh, jay

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by TacticalTechJay** [comment]
Denied. message.reply pings, adds a comma, then space, and the rest is the text inputted inside the function.

**Comment by ghost** [comment]
Yeah, proper grammar: @BookishWaffle, Whatever this sentence.
Improper: @BookishWaffle, whatever this sentence.

**Comment by TacticalTechJay** [comment]
Greetings, you can see that I currently using proper grammar.

**Comment by ghost** [comment]
No, it was lowercase where the supposed "text string" is supposed to be.

**Comment by ghost** [comment]
```js
OLD:  return message.reply(`please wait ${timeLeft.toFixed(1)} more second(s) before reusing the \`${command.name}\` command.`);
 NEW:  return message.reply(`Please wait ${timeLeft.toFixed(1)} more second(s) before reusing the \`${command.name}\` command.`);

OLD: message.reply(`there was an error trying to execute that command! Report this to the creator of this bot: \`${error}\``);
NEW: message.reply(`There was an error trying to execute that command! Report this to the creator of this bot: \`${error}\``);```

**Comment by TacticalTechJay** [comment]
Eh fuck it. I'll do it.

**Comment by ghost** [comment]
you better :angry:

**Pull request merged**
